---
title: "Parkrun round-up"
output: html_notebook
params:
  athletes: !r c(25103, 733446, 937323, 25102, 519832, 520109)
  athletes_pronoun: !r c("his", "his", "her", "her", "her", "his")
  junior_athletes: !r c(5066803, 5066873)
  junior_pronoun: !r c("her", "her")
  event_date: !r Sys.Date()
---

```{r setup, include=FALSE}
source("common-functions.R")
```

```{r get_data, include=FALSE}
# Decide which athlete IDs to use depending on day of the week and special days
# First check if it's New Year's Day or Christmas Day
if ((month(params$event_date) == 12 & day(params$event_date) == 25) |
    (month(params$event_date) == 1 & day(params$event_date) == 1)) {
      athletes <- params$athletes
      pronouns <- params$athletes_pronoun
} else if (wday(params$event_date) == 1) {
  athletes <- params$junior_athletes
  pronouns <- params$junior_pronoun
} else {
  athletes <- params$athletes
  pronouns <- params$athletes_pronoun
}
# Scrape the Parkrun website to get the data for this report
results <- map(athletes, get_all_runs)
# Generate text to display later
```

## `r params$event_date`

```{r echo = FALSE, results = "asis"}
for (ii in seq(length(results))) {
  current <- results[[ii]]
  cat(generate_report_text(template_run, template_no_run, params$event_date,
                           current, pronouns[ii]), "\n")
}
```

## Box and whiskers plot for all runs

```{r boxplots, echo = FALSE, warning = FALSE}
boxplot_df <- map_dfr(results, generate_boxplot_dataframe)
ggplot(boxplot_df, aes(x = name, y = time, fill = name)) + 
  geom_boxplot() +
  # geom_dotplot(binaxis = "y", stackdir = "center", dotsize = 1) +
  # geom_jitter(shape=16, position = position_jitter(0.2)) +
  ylab("Parkrun time (minutes)") +
  xlab("Name")
```

## Last 5 Parkruns

```{r last_5_runs, echo = FALSE, warning = FALSE}
last_5_runs <- map_dfr(results, get_last_5_runs)
last_5_runs$time <- last_5_runs$time / 60
plot_ly(last_5_runs, x = ~n, y = ~time, group = ~name, color = ~name,
        type = "scatter", mode = "lines+markers",
        hoverinfo = "text",
        hovertext = paste0(last_5_runs$name, ": ", last_5_runs$event, "<br>",
                           last_5_runs$date, " ", floor(last_5_runs$time), "M ",
                           round((last_5_runs$time -
                                    floor(last_5_runs$time)) * 60,
                                 digits = 0), "S")) %>%
  layout(hovermode = "compare",
         xaxis = list(title = "",
                      showticklabels = FALSE,
                      fixedrange=TRUE),
         yaxis = list(title = "Time (minutes)",
                      fixedrange=TRUE))
```

